Update black to 22.3
* Bump to fix `ImportError: cannot import name _unicodefun from click`
* Rebuild requirements.txt with pip-compile --generate-hashes --upgrade